fantasticlamp/fantasticlamp/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("note/", include("note.urls", namespace='note')),
    path("users/", include("users.urls"))
]

fantasticlamp/note/urls.py
from django.urls import path
from . import views
app_name = 'note'
urlpatterns = [
    path("", views.index, name="index"),
    path("inscription/<id>", views.inscription, name="inscription"),
    path("add", views.add, name="add"),
    path("update/<id>", views.update, name="update"),
    path("delete/<id>", views.delete, name="delete"),

    # path("search", views.search, name="search")
]

fantasticlamp/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

fantasticlamp/note/models.py
from django.db import models

# Create your models here.


class Inscription(models.Model):
    title = models.CharField(max_length=64)
    desc = models.CharField(max_length=100, blank=True)
    content = models.TextField(max_length=300)
    date_created = models.DateTimeField()
    cover = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return self.title


class Images(models.Model):
    image = models.ImageField(upload_to='InscriptionImages')
    inscription = models.ForeignKey(Inscription, on_delete=models.CASCADE)
    image_text = models.CharField(max_length=64)

    def __str__(self):
        return self.image_text

fantasticlamp/users/models.py
from django.db import models

# Create your models here.

fantasticlamp/note/forms.py
from django.utils import timezone

from django import forms
from .models import Inscription


class InscriptionForm(forms.ModelForm):
    def clean_date_created(self):
        data = self.cleaned_data['date_created']
        if data < timezone.now():
            data = timezone.now()
        return data

    def clean_cover(self):
        data = self.cleaned_data['cover']
        if data == "":
            data = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSo90D-727qw6WMKpUCl0mpzBa5TLFqvsTfPg&usqp=CAU"
        return data

    class Meta:
        model = Inscription
        fields = ['title', 'desc', 'content', 'date_created', 'cover']
        labels = {'title': ('Title'), 'desc': ('Description'), 'date_created': ('Date Created'), 'cover': ('Cover picture')}
        help_texts = {'desc': ('Provide a brief description of note'), 'cover': ('Provide a link to an image')}

fantasticlamp/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    # first = forms.CharField(max_length=64)
    # last = forms.CharField(max_length=64)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

fantasticlamp/note/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Inscription
from .forms import InscriptionForm
# Create your views here.


def index(request):
    return render(request, "note/index.html", {
        "inscriptions": Inscription.objects.all()
    })


def inscription(request, id):
    inscription = get_object_or_404(Inscription, id=id)
    return render(request, "note/inscription.html", {
        "inscription": inscription
    })


def add(request):
    form = InscriptionForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect("note:index")
    return render(request, "note/addinscription.html", {
        "form": form
    })


def update(request, id):
    inscription = Inscription.objects.get(id=id)
    form = InscriptionForm(request.POST or None, instance=inscription)
    if form.is_valid():
        form.save()
        return redirect("note:index")
    return render(request, "note/addinscription.html", {
        "form": form,
        "inscription": inscription
    })


def delete(request, id):
    inscription = Inscription.objects.get(id=id)
    if request.method == 'POST':
        inscription.delete()
        return redirect('note:index')
    return render(request, 'note/inscr-delete.html', {
        'inscription': inscription
    })




"""
def search(request):
    q = request.GET.get('q').strip()
    return render(request, "note/SearchResults.html", {
        "": util.search_results(q.lower()),
        "q": q
    })
"""

fantasticlamp/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from .forms import RegisterForm

# Create your views here.
from django.urls import reverse


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("login"))
    return render(request, "users/user.html")


def login_view(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "users/login.html", {
                "message": "Invalid Credentials."
            })
    return render(request, "users/login.html")


def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {
        "message": "Logged out."
    })


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "users/login.html", {
                "message": "User registered successfully. Login to continue."
            })
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {
        "form": form
    })

fantasticlamp/note/templates/note/addinscription.html
{% extends "note/layout.html" %}

{% block title %}
    New Note
{% endblock %}

{% block body %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
{% endblock %}

fantasticlamp/note/templates/note/index.html
{% extends "note/layout.html" %}

{% block title %}
    Note
{% endblock %}

{% block body %}
    <h1>Inscriptions - - -</h1>

    <ul>
        {% for inscription in inscriptions %}
        <div class="row">
            <div class="col-md-3 offset-md-1">
                <img class="card" height="150px" src="{{ inscription.cover}}">
            </div>
            <div class="col-md-4">
                <h3>{{ inscription.title }}</h3>
                <h5>{{ inscription.desc }}</h5>
            </div>
            <div class="col-md-2">
                <a href="{% url 'note:inscription' inscription.id %}" class="btn btn-success">Open</a>
            </div>
        </div>
        {% endfor %}
    </ul>

{% endblock %}

fantasticlamp/note/templates/note/inscr-delete.html
<form method="post">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ inscription.title }}?</h2>
    <button type="submit">Confirm</button>
</form>

fantasticlamp/note/templates/note/inscription.html
{% extends "note/layout.html" %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <img src="{{ inscription.cover }}" alt="cover" class="card">
        </div>
        <div class="col-md-9">
            <h1>{{ inscription.title }}</h1>
            <h5> {{ inscription.desc }}</h5>
            <div>{{ inscription.content | safe | linebreaks }}</div>
            <a href="{% url 'note:delete' inscription.id %}">Delete</a>
            <a href="{% url 'note:update' inscription.id %}">Update</a>
        </div>
    </div>
</div>






{% endblock %}

fantasticlamp/note/templates/note/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <a href="#" class="navbar-brand">Note</a>
            <div class="navbar">
                <a class="nav-item nav-link" href="{% url 'note:add' %}">New Note</a>
                <a class="nav-item nav-link" href="{% url 'note:index' %}">Home</a>
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    <a class="nav-item nav-link" href="{% url 'index' %}">Profile</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                {% endif %}
            </div>

        </nav>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                {% if user.is_authenticated %}
                <h2>Welcome {{ request.user.username }}</h2>
                {% endif %}
                <h3>Search Note</h3>
                <form>
                    <input class="search" type="text" name="q" placeholder="Search Notes">
                </form>
                <div>
                    <a href="{% url 'note:index' %}">Home</a>
                </div>
                <div>
                    Create New Page
                </div>
                <div>
                    Random Page
                </div>
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

fantasticlamp/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

fantasticlamp/users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body %}

    {% if message %}
    <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password", name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>
    <div>
        Don't have an account?
        <a href="{% url 'register' %}">Register now!</a>
    </div>
{% endblock %}

fantasticlamp/users/templates/users/register.html
{% extends "users/layout.html" %}

{% block body %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
</form>

{% endblock %}

fantasticlamp/users/templates/users/user.html
{% extends "users/layout.html" %}
{% block body %}
    <h1>Welcome, {{ request.user.first_name }}</h1>
    <ul>
        <li>Username:{{ request.user.username }}</li>
        <li>Email: {{ request.user.email }}</li>
    </ul>
    <a href="{% url 'logout' %}">Logout</a>
    <a href="{% url 'note:index' %}">Note</a>
{% endblock %}